---

# -------------------------------------------------------------------
# Python settings
# -------------------------------------------------------------------
python:
  bin_path: /anaconda3/bin
  include_path: /anaconda3/include/python3.7m


# -------------------------------------------------------------------
# PyPI settings
# -------------------------------------------------------------------
pypi:
  # credentials on test.pypi.org
  test:
    username:
    password:
  # credentials on pypi.org
  prod:
    username:
    password:


# -------------------------------------------------------------------
# Bintray settings
# -------------------------------------------------------------------
bintray:
  user:
  key: