---
# -------------------------------------------------------------------
# Python settings
# -------------------------------------------------------------------

# Python bin path (for building datalore-plot python package)
python_bin_path: /anaconda3/bin
# Python include path (for building datalore-plot python package)
python_include_path: /anaconda3/include/python3.7m

# PyPI repository url
python_repository_url:

# PyPI credentials for publishing
pypi_username:
pypi_password:


# -------------------------------------------------------------------
# Bintray settings
# -------------------------------------------------------------------

# Bintray credentials
bintray_user:
bintray_key: