---

name: ignored
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - pip
  - pip:                            # Packages installed from PyPI
      - lets-plot
