---

name: ignored
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - pip
  - pip:                            # Packages installed from PyPI
      - https://jetbrains.bintray.com/lets-plot/lets_plot-1.1.dev1-cp37-cp37m-manylinux1_x86_64.whl
      - pypng
      - scikit-datasets
