---

name: ignored
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:                            # Packages installed from PyPI
      - https://test.pypi.org/simple/ lets-plot==1.0.dev1
      - pypng
      - scikit-datasets
