---

name: ignored
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:                            # Packages installed from PyPI
      - https://test-files.pythonhosted.org/packages/fb/eb/f74b96d7416bbccf36693df808ca1c4faa2243083bb5308f692fb1264a42/lets_plot-1.0.dev1-cp37-cp37m-manylinux1_x86_64.whl
      - pypng
      - scikit-datasets
